// ══════════════════════════════════════════════════════════════
// LAYER DEFINITIONS — Verified ArcGIS REST / WMS / WFS endpoints
// National: PCN (www.pcn.minambiente.it), ISPRA, MiC
// Regional: Geoportali regionali ufficiali
// ══════════════════════════════════════════════════════════════

export interface LayerDef {
  id: string;
  label: string;
  color: string;
  defaultOn: boolean;
  wmsUrl?: string;
  wmsLayer?: string;
  wfsUrl?: string;
  wfsLayer?: string;
  arcgisUrl?: string;
  arcgisLayers?: string;
  srid?: string;
  opacity?: number;
  description?: string;
  /** Bounding box [south, west, north, east] — layer only loads when map intersects */
  bounds?: [number, number, number, number];
  /** Alternative ArcGIS/WMS URLs to try if the primary is offline */
  fallbackUrls?: string[];
  /** Skip TLS certificate verification for this layer */
  tlsBypass?: boolean;
}

export interface LayerGroup {
  id: string;
  label: string;
  icon: string;
  layers: LayerDef[];
}

export const LAYER_GROUPS: LayerGroup[] = [
  // ── CATASTO ──────────────────────────────────────────────────
  {
    id: "catasto",
    label: "Catasto",
    icon: "🗺️",
    layers: [
      {
        id: "catasto",
        label: "Catasto particellare",
        color: "#f59e0b",
        defaultOn: true,
        description: "Particelle catastali ufficiali (Agenzia delle Entrate)",
        srid: "25832",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // A. VINCOLI D.LGS. 42/2004 (CODICE DEI BENI CULTURALI E DEL PAESAGGIO)
  // ══════════════════════════════════════════════════════════════

  // ── A1. Beni paesaggistici Art. 136 (bellezze individue e di insieme) ──
  {
    id: "beni_paesaggistici_136",
    label: "A1. Beni Paesaggistici Art. 136",
    icon: "🏛️",
    layers: [
      {
        id: "sitap_vincoli_136",
        label: "Vincoli Art. 136/157 (decretati) — SITAP",
        color: "#7c3aed",
        defaultOn: false,
        wmsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayer: "sitap_ws:wms_sitap_v1497_pol_136",
        wfsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wfs",
        wfsLayer: "sitap_ws:wms_sitap_v1497_pol_136",
        // arcgisUrl: sig.beniculturali.it is dead (DNS failure) — SITAP WMS is the primary source
        srid: "32632",
        opacity: 0.55,
        description: "Vincoli paesaggistici 'decretati' Art. 136/157 D.Lgs. 42/2004 — SITAP MiC",
      },
      {
        id: "vincoli_art136_142",
        label: "Vincoli Art. 136/142 — ISPRA PITESAI",
        color: "#9333ea",
        defaultOn: false,
        arcgisUrl: "https://sinacloud.isprambiente.it/arcgisina/rest/services/PITESAI/PITESAI_Strati_II_livello/MapServer",
        arcgisLayers: "show:42",
        srid: "32632",
        opacity: 0.55,
        description: "Aree vincolate ai sensi del D.Lgs. 42/2004 Art. 136 e 142 — ISPRA PITESAI",
      },
      {
        id: "rischio_beni_esposti",
        label: "Rischio beni culturali esposti",
        color: "#c084fc",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Rischio_beni_esposti/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Beni culturali e ambientali esposti a rischio — PCN",
      },
      {
        id: "vir_aree_archeologiche",
        label: "Aree archeologiche vincolate (VIR)",
        color: "#b45309",
        defaultOn: false,
        wmsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayer: "sitap_ws:tab_vir_geo_aree_archeol_vincolate",
        wfsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wfs",
        wfsLayer: "sitap_ws:tab_vir_geo_aree_archeol_vincolate",
        srid: "32632",
        opacity: 0.55,
        description: "Aree archeologiche vincolate — Vincoli in Rete / Carta del Rischio (MiC)",
      },
      {
        id: "sitap_alberi_monumentali",
        label: "Alberi monumentali d'Italia",
        color: "#15803d",
        defaultOn: false,
        wmsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws_clone/wms",
        wmsLayer: "sitap_ws_clone:alberi_monumentali",
        wfsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws_clone/wfs",
        wfsLayer: "sitap_ws_clone:alberi_monumentali",
        srid: "32632",
        opacity: 0.6,
        description: "Elenco degli alberi monumentali d'Italia — MiC / SITAP",
      },
    ],
  },

  // ── A2. Beni paesaggistici Art. 142 (vincoli ope legis) ──
  {
    id: "paesaggistici_142",
    label: "A2. Vincoli Paesaggistici Art. 142",
    icon: "🏞️",
    layers: [
      {
        id: "art142_a_costieri",
        label: "a) Territori costieri (300m)",
        color: "#0284c7",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_aree_di_rispetto",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. a — Territori costieri entro 300m dalla linea di battigia",
      },
      {
        id: "art142_b_laghi",
        label: "b) Laghi (300m)",
        color: "#0369a1",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:1",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_aree_di_rispetto",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. b — Territori contermini ai laghi entro 300m",
      },
      {
        id: "art142_c_fiumi",
        label: "c) Fiumi e corsi d'acqua (150m)",
        color: "#2563eb",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:2",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_aree_di_rispetto",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. c — Fiumi, torrenti, corsi d'acqua e relative sponde (150m)",
      },
      {
        id: "art142_d_montagne",
        label: "d) Montagne >1.200m",
        color: "#7c3aed",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:3",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_zone_altimetriche",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. d — Montagne per la parte eccedente 1.200m s.l.m.",
      },
      {
        id: "art142_e_ghiacciai",
        label: "e) Ghiacciai e circhi glaciali",
        color: "#38bdf8",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:4",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. e — Ghiacciai e circhi glaciali",
      },
      {
        id: "art142_f_parchi",
        label: "f) Parchi e riserve nazionali/regionali",
        color: "#16a34a",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:5",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_parchi_nazionali,sitap_ws:vw_vasvia_parchi_regionali",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. f — Parchi e riserve nazionali e regionali",
      },
      {
        id: "art142_g_boschi",
        label: "g) Boschi e foreste",
        color: "#166534",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:6",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_boschi",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. g — Territori coperti da foreste e boschi",
      },
      {
        id: "art142_h_usi_civici",
        label: "h) Usi civici",
        color: "#78716c",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:7",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:tab_usi_civici",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. h — Aree assegnate alle università agrarie e zone gravate da usi civici",
      },
      {
        id: "art142_i_zone_umide",
        label: "i) Zone umide Ramsar",
        color: "#0891b2",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:8",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_zone_umide",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. i — Zone umide incluse nell'elenco Ramsar",
      },
      {
        id: "art142_l_archeologia",
        label: "l) Zone di interesse archeologico",
        color: "#92400e",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:9",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:tab_vir_geo_aree_archeol_vincolate",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. l — Zone di interesse archeologico",
      },
      {
        id: "art142_m_vulcani",
        label: "m) Vulcani e fasce di rispetto",
        color: "#dc2626",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:10",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Vincoli_Paesaggistici_Art142.map",
        wmsLayer: "Vincoli_Paesaggistici_Art142",
        wmsUrlFallback: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayerFallback: "sitap_ws:vw_vasvia_vulcani",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Art. 142 c.1 lett. m — Vulcani e fasce di rispetto vulcaniche",
      },
    ],
  },

  // ── A3. Dichiarazioni di notevole interesse pubblico ──
  {
    id: "notevole_interesse",
    label: "A3. Dichiarazioni Notevole Interesse Pubblico",
    icon: "📜",
    layers: [
      {
        id: "dip_geoportale",
        label: "Dichiarazioni notevole interesse (PCN)",
        color: "#a855f7",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Vincoli_Paesaggistici_Art142/MapServer",
        arcgisLayers: "show:11",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Dichiarazioni di notevole interesse pubblico — Geoportale Nazionale",
      },
      {
        id: "dip_sitap_bellezze_individue",
        label: "Bellezze individue (SITAP)",
        color: "#8b5cf6",
        defaultOn: false,
        wmsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayer: "sitap_ws:wms_sitap_v1497_pol_136",
        wfsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wfs",
        wfsLayer: "sitap_ws:wms_sitap_v1497_pol_136",
        srid: "32632",
        opacity: 0.55,
        description: "Bellezze individue — Dichiarazioni di notevole interesse pubblico (D.M.) — SITAP MiC",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // B. AREE PROTETTE
  // ══════════════════════════════════════════════════════════════
  {
    id: "aree_protette",
    label: "B. Aree Protette",
    icon: "🌿",
    layers: [
      {
        id: "aree_protette_euap",
        label: "B1-B6. Aree protette (EUAP)",
        color: "#16a34a",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/EUAP/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/EUAP.map",
        wmsLayer: "SP.SITIPROTETTI.EUAP",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "SP.SITIPROTETTI.EUAP",
        srid: "32632",
        opacity: 0.5,
        description: "Elenco Ufficiale Aree Protette: parchi nazionali, regionali, riserve statali/regionali, AMP (L. 394/1991)",
      },
      {
        id: "pelagos",
        label: "Santuario Pelagos",
        color: "#06b6d4",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Santuario_Pelagos/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Santuario_Pelagos.map",
        wmsLayer: "SP.SITIPROTETTI.Santuario_Pelagos",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "SP.SITIPROTETTI.Santuario_Pelagos",
        srid: "32632",
        opacity: 0.5,
        description: "Santuario dei Cetacei (Accordo Pelagos)",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // C. RETE NATURA 2000
  // ══════════════════════════════════════════════════════════════
  {
    id: "natura2000",
    label: "C. Rete Natura 2000",
    icon: "🦎",
    layers: [
      {
        id: "natura2000_sic_zsc",
        label: "C1. ZSC / ex SIC (Dir. Habitat)",
        color: "#10b981",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/SIC_ZSC_ZPS/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/SIC_ZSC_ZPS.map",
        wmsLayer: "SP.SITIPROTETTI.SIC_ZSC_ZPS",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "SP.SITIPROTETTI.SIC_ZSC_ZPS",
        srid: "3003",
        opacity: 0.55,
        description: "Zone Speciali di Conservazione (ZSC / ex SIC) — Dir. 92/43/CEE Habitat",
      },
      {
        id: "natura2000_zps",
        label: "C2. ZPS (Dir. Uccelli)",
        color: "#059669",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/SIC_ZSC_ZPS/MapServer",
        arcgisLayers: "show:1",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/SIC_ZSC_ZPS.map",
        wmsLayer: "SP.SITIPROTETTI.SIC_ZSC_ZPS",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "SP.SITIPROTETTI.SIC_ZSC_ZPS",
        srid: "3003",
        opacity: 0.55,
        description: "Zone di Protezione Speciale (ZPS) — Dir. 79/409/CEE Uccelli",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // D. SITI UNESCO
  // ══════════════════════════════════════════════════════════════
  {
    id: "unesco",
    label: "D. Siti UNESCO",
    icon: "🏰",
    layers: [
      {
        id: "unesco_sites",
        label: "D1. Patrimonio Mondiale UNESCO",
        color: "#8B008B",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/UNESCO/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.4,
        description: "Siti del Patrimonio Mondiale UNESCO in Italia — buffer 5 km",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // E. VINCOLI IDROGEOLOGICI
  // ══════════════════════════════════════════════════════════════
  {
    id: "vincoli_idrogeologici",
    label: "E. Vincoli Idrogeologici",
    icon: "🌊",
    layers: [
      {
        id: "vincolo_idrogeologico",
        label: "E1. Vincolo idrogeologico (R.D. 3267/1923)",
        color: "#1d4ed8",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/PAI_pericolosita_idrogeologica/MapServer",
        arcgisLayers: "show:2",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/PAI_pericolosita.map",
        wmsLayer: "RN.PAI.PERICOLOSITA.FRANA_01",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Aree sottoposte a vincolo idrogeologico — R.D. 3267/1923",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/PAI_Frane/Aree_pericolosita_frana_PAI/MapServer"],
      },
      {
        id: "frane_iffi",
        label: "E2. Frane IFFI (poligonali)",
        color: "#ef4444",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Catalogo_Frane_Frane_poligonali/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Catalogo_Frane.map",
        wmsLayer: "GE.GeologicalUnit.CatalogoFrane",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "GE.GeologicalUnit.CatalogoFrane",
        srid: "32632",
        opacity: 0.55,
        description: "Inventario Fenomeni Franosi in Italia (ISPRA IFFI) — frane poligonali",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/iffi/Progetto_IFFI_WMS_public/MapServer"],
      },
      {
        id: "frane_lineari",
        label: "E2. Frane IFFI (lineari)",
        color: "#f87171",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Catalogo_Frane_Frane_lineari/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Catalogo_Frane.map",
        wmsLayer: "GE.GeologicalUnit.CatalogoFrane",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "IFFI — frane lineari",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/iffi/Progetto_IFFI_WMS_public/MapServer"],
      },
      {
        id: "frane_dgpv",
        label: "E2. Frane IFFI (DGPV)",
        color: "#b91c1c",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Catalogo_Frane_DGPV/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Catalogo_Frane.map",
        wmsLayer: "GE.GeologicalUnit.CatalogoFrane",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "IFFI — Deformazioni Gravititative Profonde di Versante",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/iffi/Progetto_IFFI_WMS_public/MapServer"],
      },
      {
        id: "frane_aree",
        label: "E2. Frane IFFI (aree)",
        color: "#fca5a5",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Catalogo_Frane_Aree/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Catalogo_Frane.map",
        wmsLayer: "GE.GeologicalUnit.CatalogoFrane",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "IFFI — aree soggette a frana",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/iffi/Progetto_IFFI_WMS_public/MapServer"],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // E2. PERICOLOSITÀ IDROGEO (ISPRA 2024)
  // ══════════════════════════════════════════════════════════════
  {
    id: "idrogeo_ispra",
    label: "E2. Pericolosità IdroGEO (ISPRA 2024)",
    icon: "🌊",
    layers: [
      {
        id: "idrogeo_frane_p4",
        label: "Pericolosità frana molto elevata P4 (IdroGEO)",
        color: "#7f0000",
        defaultOn: false,
        arcgisUrl: "https://idrogeo.isprambiente.it/arcgis/rest/services/PAIFrane/Aree_pericolosita_frana_PAI/MapServer",
        arcgisLayers: "show:0",
        opacity: 0.6,
        description: "Mosaicatura ISPRA PAI pericolosità da frana P4 (molto elevata) — IdroGEO 2024. Alternativa più aggiornata al PCN.",
      },
      {
        id: "idrogeo_frane_p3",
        label: "Pericolosità frana elevata P3 (IdroGEO)",
        color: "#dc2626",
        defaultOn: false,
        arcgisUrl: "https://idrogeo.isprambiente.it/arcgis/rest/services/PAIFrane/Aree_pericolosita_frana_PAI/MapServer",
        arcgisLayers: "show:1",
        opacity: 0.55,
        description: "Mosaicatura ISPRA PAI pericolosità da frana P3 (elevata) — IdroGEO 2024.",
      },
      {
        id: "idrogeo_alluvioni_p3",
        label: "Pericolosità idraulica elevata P3 (IdroGEO)",
        color: "#1d4ed8",
        defaultOn: false,
        arcgisUrl: "https://idrogeo.isprambiente.it/arcgis/rest/services/PAIAlluvioni/Aree_pericolosita_idraulica/MapServer",
        arcgisLayers: "show:0",
        opacity: 0.55,
        description: "Mosaicatura ISPRA pericolosità idraulica P3 (TR 20-50 anni) — IdroGEO 2024.",
      },
      {
        id: "idrogeo_alluvioni_p2",
        label: "Pericolosità idraulica media P2 (IdroGEO)",
        color: "#3b82f6",
        defaultOn: false,
        arcgisUrl: "https://idrogeo.isprambiente.it/arcgis/rest/services/PAIAlluvioni/Aree_pericolosita_idraulica/MapServer",
        arcgisLayers: "show:1",
        opacity: 0.5,
        description: "Mosaicatura ISPRA pericolosità idraulica P2 (TR 100-200 anni) — IdroGEO 2024.",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // F. RISCHIO FRANA (PAI)
  // ══════════════════════════════════════════════════════════════
  {
    id: "rischio_frana",
    label: "F. Rischio Frana (PAI)",
    icon: "⛰️",
    layers: [
      {
        id: "pai_frane",
        label: "F1-F4. PAI — Pericolosità frana (P1→P4)",
        color: "#dc2626",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/PAI_pericolosita_idrogeologica/MapServer",
        arcgisLayers: "show:1",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/PAI_pericolosita.map",
        wmsLayer: "RN.PAI.PERICOLOSITA.FRANA_01,RN.PAI.PERICOLOSITA.FRANA_02",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Mosaicatura PAI — Pericolosità da frana P1→P4",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/PAI_Frane/Aree_pericolosita_frana_PAI/MapServer"],
      },
      {
        id: "pai_rischio",
        label: "PAI — Rischio idrogeologico (R1→R4)",
        color: "#7c3aed",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/PAI_rischio_idrogeologico/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/PAI_rischio.map",
        wmsLayer: "RN.PAI.RISCHIO.ALLUVIONE,RN.PAI.RISCHIO.FRANA_01,RN.PAI.RISCHIO.FRANA_02",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Mosaicatura PAI — Classi di rischio (R1→R4)",
      },
      {
        id: "geologia",
        label: "Carta geologica d'Italia",
        color: "#b45309",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/geologica/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Carta_geologica.map",
        wmsLayer: "GE.GeologicalUnit",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Carta Geologica d'Italia (ISPRA — Servizio Geologico)",
      },
      {
        id: "geolitologica",
        label: "Carta geolitologica",
        color: "#92400e",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/geolitologica/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Carta_geolitologica.map",
        wmsLayer: "GE.GeologicalUnit.geolitologica",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Carta geolitologica d'Italia",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // G. RISCHIO ALLUVIONE (PGRA)
  // ══════════════════════════════════════════════════════════════
  {
    id: "rischio_alluvione",
    label: "G. Rischio Alluvione (PGRA)",
    icon: "🌊",
    layers: [
      {
        id: "pai_alluvioni",
        label: "G1-G3. PAI — Pericolosità alluvionale",
        color: "#2563eb",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/PAI_pericolosita_idrogeologica/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/PAI_pericolosita.map",
        wmsLayer: "RN.PAI.PERICOLOSITA.ALLUVIONE",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Mosaicatura PAI — Pericolosità da alluvione (P1→P3)",
        fallbackUrls: ["https://sinacloud.isprambiente.it/arcgisina/rest/services/Alluvioni/Aree_pericolosita_idraulica_/MapServer"],
      },
      {
        id: "alluvioni_estensione",
        label: "PGRA — Aree allagabili",
        color: "#0ea5e9",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Alluvioni_Estensione/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Alluvioni_Estensione.map",
        wmsLayer: "Alluvioni_Estensione",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Estensione aree allagabili (Dir. 2007/60/CE — D.Lgs. 49/2010)",
      },
      {
        id: "alluvioni_rischio",
        label: "PGRA — Classi di rischio alluvionale",
        color: "#1e40af",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Alluvioni_Classi_di_Rischio/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Alluvioni_Classi_di_Rischio.map",
        wmsLayer: "Alluvioni_Classi_di_Rischio",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Classi di rischio alluvionale (Dir. 2007/60/CE)",
      },
      {
        id: "alluvioni_idrauliche",
        label: "PGRA — Caratteristiche idrauliche",
        color: "#3b82f6",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Alluvioni_Caratteristiche_Idrauliche/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Alluvioni_Caratteristiche_Idrauliche.map",
        wmsLayer: "Alluvioni_Caratteristiche_Idrauliche",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Caratteristiche idrauliche delle aree allagabili",
      },
      {
        id: "alluvioni_elementi",
        label: "PGRA — Elementi a rischio",
        color: "#6366f1",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Alluvioni_ElementiRischio/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Alluvioni_Elementi_a_Rischio.map",
        wmsLayer: "Alluvioni_Elementi_a_Rischio",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Elementi esposti al rischio di alluvione",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // H. AUTORITÀ DI BACINO DISTRETTUALI
  // ══════════════════════════════════════════════════════════════
  {
    id: "autorita_bacino",
    label: "H. Autorità di Bacino Distrettuali",
    icon: "🏞️",
    layers: [
      {
        id: "adb",
        label: "Perimetri Autorità di Bacino",
        color: "#4b5563",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/ADB/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Limiti_Amministativi_AdBD_2018.map",
        wmsLayer: "AU.AdministrativeUnit.AdBD",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Perimetri delle Autorità di Bacino Distrettuale (7 distretti idrografici)",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // I. VINCOLI URBANISTICI
  // ══════════════════════════════════════════════════════════════
  {
    id: "vincoli_urbanistici",
    label: "I. Vincoli Urbanistici",
    icon: "🏘️",
    layers: [
      {
        id: "limiti_admin",
        label: "Limiti amministrativi 2020",
        color: "#6b7280",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Limiti_amministrativi_2020/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/LimitiAmministrativi_2020.map",
        wmsLayer: "AU.AdministrativeUnit",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Limiti comunali, provinciali e regionali (ISTAT 2020)",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // L. RETE ECOLOGICA E ALTRI VINCOLI AMBIENTALI
  // ══════════════════════════════════════════════════════════════
  {
    id: "rete_ecologica",
    label: "L. Rete Ecologica & Biodiversità",
    icon: "🦋",
    layers: [
      {
        id: "ren",
        label: "L1. Rete Ecologica Nazionale (REN)",
        color: "#059669",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Rete_Ecologica_Nazionale/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Rete Ecologica Nazionale — corridoi e aree nucleo",
      },
      {
        id: "iba",
        label: "L2. IBA — Important Bird Areas",
        color: "#22d3ee",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/iba/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/IBA.map",
        wmsLayer: "SP.SITIPROTETTI.IBA",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "SP.SITIPROTETTI.IBA",
        srid: "32632",
        opacity: 0.5,
        description: "Important Bird and Biodiversity Areas (BirdLife International / LIPU)",
      },
      {
        id: "ramsar",
        label: "L3. Zone umide RAMSAR",
        color: "#0891b2",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/aree_ramsar/MapServer",
        arcgisLayers: "show:0",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/RAMSAR.map",
        wmsLayer: "SP.SITIPROTETTI.RAMSAR",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wfsLayer: "SP.SITIPROTETTI.RAMSAR",
        srid: "32632",
        opacity: 0.55,
        description: "Zone umide di importanza internazionale (Convenzione Ramsar 1971)",
      },
      {
        id: "zone_umide",
        label: "L3. Zone umide e paludi",
        color: "#0e7490",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Zone_umide/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Aree umide e paludi d'Italia",
      },
      {
        id: "inventario_forestale",
        label: "Inventario Forestale Nazionale (INFC)",
        color: "#166534",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Inventario_Forestale_Nazionale_2015/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Inventario Nazionale delle Foreste e dei serbatoi forestali di Carbonio",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // M. INFRASTRUTTURE — BUFFER DI RISPETTO
  // ══════════════════════════════════════════════════════════════
  {
    id: "infrastrutture",
    label: "M. Infrastrutture & Buffer",
    icon: "⚡",
    layers: [
      {
        id: "elettrodotti",
        label: "M1. Elettrodotti AT/AAT (buffer 150m)",
        color: "#FFFF00",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/elettrodotti/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Linee elettriche Alta/Altissima Tensione — buffer DPA 150m (DM 29/05/2008)",
      },
      {
        id: "gasdotti",
        label: "M2. Gasdotti principali (buffer 200m)",
        color: "#f59e0b",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/gasdotti/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Rete gasdotti principali (Snam) — buffer 200m",
      },
      {
        id: "strade_principali",
        label: "M4. Strade statali e autostrade",
        color: "#9ca3af",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/strade/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?service=wms&layer=strade",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Rete stradale — fasce rispetto DPR 495/1992 (60m autostrade, 40m statali, 30m provinciali)",
      },
      {
        id: "ferrovie",
        label: "Ferrovie (fascia 50m DPR 753/1980)",
        color: "#374151",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/ferrovie/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map",
        wmsLayer: "TN.RailTransportNetwork.RailwayLink",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Rete ferroviaria italiana — fascia rispetto 50m (DPR 753/1980)",
      },
      {
        id: "porti",
        label: "Porti",
        color: "#1f2937",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Porti_2012/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Porti marittimi italiani",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // N. AREE IDONEE E NON IDONEE — FOTOVOLTAICO / AGRIVOLTAICO
  // ══════════════════════════════════════════════════════════════
  {
    id: "fotovoltaico",
    label: "N. Fotovoltaico & Aree Idonee/Non Idonee",
    icon: "☀️",
    layers: [
      {
        id: "aree_idonee_fer",
        label: "N1. Aree idonee FER (D.Lgs. 199/2021)",
        color: "#00FF7F",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Aree_idonee_FER/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "4326",
        opacity: 0.35,
        description: "Aree idonee ex lege — D.Lgs. 199/2021 art. 20 (cave, discariche, siti contaminati, zone industriali)",
      },
      {
        id: "aree_non_idonee_fer",
        label: "N2. Aree non idonee FER (DM 10/09/2010)",
        color: "#808080",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Aree_non_idonee_FER/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "4326",
        opacity: 0.4,
        description: "Aree non idonee — DM 10/09/2010 (Linee Guida nazionali FER)",
      },
      {
        id: "doc_docg",
        label: "N3. Zone DOC/DOCG vitivinicole",
        color: "#7f1d1d",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/DOC_DOCG/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.4,
        description: "Delimitazioni zone DOC/DOCG — aree agricole di pregio",
      },
      {
        id: "dop_igp",
        label: "N3. Zone DOP/IGP agricole",
        color: "#92400e",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/DOP_IGP/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.4,
        description: "Aree DOP/IGP — zone di pregio per agrivoltaico",
      },
      {
        id: "impianti_fer",
        label: "Impianti FER esistenti (GSE)",
        color: "#22c55e",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Impianti_FER/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "4326",
        opacity: 0.45,
        description: "Impianti a fonti rinnovabili censiti dal GSE",
      },
      {
        id: "irradianza_globale",
        label: "Irradianza solare globale (media annua)",
        color: "#f59e0b",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/irradianza_solare/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Irradianza solare globale media annuale (kWh/m²/anno) — ENEA/RSE",
      },
      {
        id: "irradianza_diretta",
        label: "Irradianza diretta normale (DNI)",
        color: "#d97706",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/irradianza_solare_diretta/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Irradianza diretta normale media annuale",
      },
      {
        id: "siti_contaminati",
        label: "N1. Siti contaminati (SIN/SIR) — aree idonee",
        color: "#991b1b",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/siti_contaminati/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?service=wms&layer=aree_contaminate",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Siti di Interesse Nazionale per le bonifiche — potenziali aree idonee FER",
      },
      {
        id: "cave_miniere",
        label: "N1. Cave e miniere dismesse — aree idonee",
        color: "#78716c",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/cave_miniere/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Cave e miniere dismesse — potenziali aree idonee FER (D.Lgs. 199/2021)",
      },
      {
        id: "toscana_aree_non_idonee_pv",
        label: "Aree non idonee FV Toscana (GEOscopio)",
        color: "#dc2626",
        defaultOn: false,
        wmsUrl: "https://www502.regione.toscana.it/geoscopio/wms",
        wmsLayer: "FONTI_RINNOVABILI",
        opacity: 0.5,
        bounds: [42.24, 9.69, 44.47, 12.37],
        description: "Perimetrazione aree non idonee all'installazione di impianti fotovoltaici a terra — Regione Toscana (GEOscopio)",
      },
      {
        id: "basilicata_impianti_eolici",
        label: "Impianti eolici Basilicata",
        color: "#22c55e",
        defaultOn: false,
        wmsUrl: "https://rsdi.regione.basilicata.it/rbgeoserver2016/wms",
        wmsLayer: "rsdi:impianti_eolici_esercizio",
        opacity: 0.6,
        bounds: [39.89, 15.33, 41.14, 16.87],
        description: "Aerogeneratori in esercizio sul territorio regionale — RSDI Basilicata",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // O. FASCE DI RISPETTO SPECIFICHE
  // ══════════════════════════════════════════════════════════════
  {
    id: "fasce_rispetto",
    label: "O. Fasce di Rispetto Specifiche",
    icon: "🚧",
    layers: [
      {
        id: "aeroporti",
        label: "O1. Aeroporti e zone di rispetto (ENAC)",
        color: "#6366f1",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/aeroporti/MapServer",
        wmsUrl: "https://geoportale.enac.gov.it/wms",
        wfsUrl: "https://geoportale.enac.gov.it/wfs",
        srid: "4326",
        opacity: 0.5,
        description: "Aeroporti e zone di rischio aeronautico (ENAC) — Zone A, B, C, D",
      },
      {
        id: "faglie_attive_capaci",
        label: "O2. Faglie Attive e Capaci (FAC)",
        color: "#dc2626",
        defaultOn: false,
        arcgisUrl: "https://sgi2.isprambiente.it/arcgis/rest/services/servizi/ithaca_new/MapServer",
        arcgisLayers: "show:0,1",
        srid: "3857",
        opacity: 0.55,
        description: "Faglie attive e capaci — inedificabilità assoluta fascia 30-160m (NTC 2018). ISPRA ITHACA / INGV",
      },
      {
        id: "rischio_seveso",
        label: "O3. Stabilimenti RIR (Rischio Seveso)",
        color: "#b91c1c",
        defaultOn: false,
        arcgisUrl: "https://annuario.isprambiente.it/arcgis/rest/services/rischio_industriale/MapServer",
        wmsUrl: "https://annuario.isprambiente.it/wms",
        wfsUrl: "https://annuario.isprambiente.it/wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Stabilimenti a Rischio di Incidente Rilevante — D.Lgs. 105/2015 (Direttiva Seveso III)",
      },
      {
        id: "metanodotti_snam",
        label: "O4. Metanodotti SNAM (fasce rispetto)",
        color: "#f59e0b",
        defaultOn: false,
        // gis.snam.it DNS failure, www.snam.it non è endpoint GIS
        // Nessun endpoint pubblico alternativo disponibile
        srid: "32632",
        opacity: 0.5,
        description: "Rete trasporto gas SNAM — fasce di rispetto D.M. 17/04/2008. ⚠️ Nessun endpoint GIS pubblico disponibile",
      },
      {
        id: "aree_militari",
        label: "O5. Aree militari",
        color: "#374151",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/aree_militari/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?service=wms&layer=aree_militari",
        srid: "32632",
        opacity: 0.45,
        description: "Aree militari, poligoni di tiro e coni radar — L. 898/1976",
      },
      {
        id: "archeologia_gnac",
        label: "O6. Vincoli archeologici (GNA/SITAP)",
        color: "#92400e",
        defaultOn: false,
        wmsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wms",
        wmsLayer: "sitap_ws:tab_vir_geo_aree_archeol_vincolate",
        wfsUrl: "https://sitap.cultura.gov.it/geoserver/sitap_ws/wfs",
        wfsLayer: "sitap_ws:tab_vir_geo_aree_archeol_vincolate",
        srid: "32632",
        opacity: 0.55,
        description: "Vincoli archeologici e aree di interesse — D.Lgs. 42/2004. SITAP MiC (GNAC non più disponibile)",
      },
      {
        id: "cimiteri_buffer",
        label: "O7. Fasce cimiteriali (200m)",
        color: "#6b7280",
        defaultOn: false,
        wmsUrl: "https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/cartografia",
        srid: "25832",
        opacity: 0.4,
        description: "Inedificabilità assoluta entro 200m dal muro di cinta — R.D. 1265/1934",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // P. SISMICA
  // ══════════════════════════════════════════════════════════════

  // ── P2. Sismicità INGV ──
  {
    id: "ingv_sismica",
    label: "P2. Sismicità INGV (aggiornato)",
    icon: "🔴",
    layers: [
      {
        id: "ingv_shakemap",
        label: "ShakeMap — scuotimento sismico recente",
        color: "#f97316",
        defaultOn: false,
        wmsUrl: "https://shakemap.rm.ingv.it/shake4/ws/event/last/shakemap/wms",
        wmsLayer: "PGA",
        opacity: 0.5,
        description: "ShakeMap INGV — accelerazione di picco al suolo (PGA) degli ultimi eventi sismici significativi",
      },
      {
        id: "ingv_pericolosita_mps04",
        label: "Pericolosità sismica MPS04 (INGV)",
        color: "#ef4444",
        defaultOn: false,
        wmsUrl: "https://esse1-gis.mi.ingv.it/ms_sito_ingv2/ms_sito.php",
        wmsLayer: "MPS04",
        opacity: 0.45,
        description: "Mappa di Pericolosità Sismica italiana MPS04 — INGV. Stessa base dati delle NTC 2018.",
      },
    ],
  },
  {
    id: "sismica",
    label: "P. Sismica",
    icon: "🔴",
    layers: [
      {
        id: "zonazione_sismica",
        label: "P1. Classificazione sismica comunale",
        color: "#f97316",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/classificazione_sismica_comunale_2012/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Classificazione_sismica_2012.map",
        wmsLayer: "NZ.ClassificazioneSismica2012",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Classificazione sismica comuni italiani (Zone 1-4) — aggiornamento 2012",
      },
      {
        id: "pericolosita_sismica_002",
        label: "P2. Pericolosità sismica (PGA 0.02)",
        color: "#ea580c",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/pericolosita_sismica_002/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Pericolosita_sismica_002.map",
        wmsLayer: "NZ.PericolositaSismica002",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Mappa pericolosità sismica — probabilità eccedenza 2% in 50 anni",
      },
      {
        id: "pericolosita_sismica_005",
        label: "P3. Pericolosità sismica (PGA 0.05)",
        color: "#c2410c",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/pericolosita_sismica_005/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Pericolosita_sismica_005.map",
        wmsLayer: "NZ.PericolositaSismica005",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Mappa pericolosità sismica — probabilità eccedenza 5% in 50 anni",
      },
      {
        id: "zone_sismogenetiche",
        label: "P4. Zone sismogenetiche ZS9",
        color: "#9a3412",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Zone_sismogenetiche_ZS9/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Zone_sismogenetiche_ZS9.map",
        wmsLayer: "NZ.ZoneSismogeneticheZS9",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Zonazione sismogenetica ZS9 (INGV)",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // Q. USO DEL SUOLO
  // ══════════════════════════════════════════════════════════════
  {
    id: "uso_suolo",
    label: "Q. Uso del Suolo",
    icon: "🌾",
    layers: [
      {
        id: "corine",
        label: "Q1. CORINE Land Cover 2012",
        color: "#65a30d",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/corine_landcover_2012/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Corine_Land_Cover2012.map",
        wmsLayer: "LC.LandCoverSurfaces.CLC2012",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "CORINE Land Cover 2012 — classificazione del territorio",
      },
      {
        id: "corine_iv",
        label: "Q1. CORINE Land Cover 2012 (IV livello)",
        color: "#4d7c0f",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/corcover_2012_IV_livello/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Corine_Land_Cover2012_IVliv.map",
        wmsLayer: "LC.LandCoverSurfaces.CLC2012_IVliv",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "CORINE Land Cover 2012 — IV livello dettaglio",
      },
      {
        id: "iuti",
        label: "Q2. IUTI — Inventario Uso Terre",
        color: "#84cc16",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/IUTI/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/IUTI.map",
        wmsLayer: "LC.LandCoverSurfaces.IUTI",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Inventario dell'Uso delle Terre d'Italia",
      },
      {
        id: "capacita_uso_suoli",
        label: "Q3. Capacità d'uso dei suoli (LCC)",
        color: "#a16207",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/capacita_uso_suoli/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?service=wms&layer=suoli",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Classi di capacità d'uso dei suoli (Land Capability Classification)",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // R. IDROGRAFIA & COSTA
  // ══════════════════════════════════════════════════════════════
  {
    id: "idrografia",
    label: "R. Idrografia & Costa",
    icon: "💧",
    layers: [
      {
        id: "aste_fluviali",
        label: "R1. Aste fluviali",
        color: "#0284c7",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/aste_fluviali/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Aste_fluviali.map",
        wmsLayer: "HY.PhysicalWaters.Watercourse",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.6,
        description: "Reticolo idrografico — aste fluviali principali e secondarie",
      },
      {
        id: "laghi",
        label: "R2. Laghi e specchi d'acqua",
        color: "#0369a1",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Laghi_specchi_acqua/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Specchi_Acqua.map",
        wmsLayer: "HY.PhysicalWaters.StandingWater",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Laghi e specchi d'acqua",
      },
      {
        id: "linea_costa",
        label: "R3. Linea di costa 2009",
        color: "#0e7490",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/linea_di_costa_2009/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Linea_costa_2009.map",
        wmsLayer: "HY.PhysicalWaters.Shore",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Linea di costa italiana — rilievo 2009",
      },
      {
        id: "variazione_costa",
        label: "R4. Variazione della costa 1960-2012",
        color: "#155e75",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Variazione_costa_1960_2012/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Variazione della linea di costa 1960-2012",
      },
      {
        id: "unita_fisiografiche",
        label: "R5. Unità fisiografiche costiere",
        color: "#164e63",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/unita_fisiografiche/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.5,
        description: "Unità fisiografiche della costa italiana",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // S. AMBIENTE & TERRITORIO
  // ══════════════════════════════════════════════════════════════
  {
    id: "territorio",
    label: "S. Ambiente & Territorio",
    icon: "🌍",
    layers: [
      {
        id: "ecopedologica",
        label: "S1. Carta ecopedologica",
        color: "#059669",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/ecopedologica/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Carta_ecopedologica.map",
        wmsLayer: "SO.SoilBody.ecopedologica",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Carta ecopedologica d'Italia",
      },
      {
        id: "fitoclima",
        label: "S2. Fitoclima",
        color: "#047857",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/fitoclima/MapServer",
        wmsUrl: "https://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Carta_fitoclimatica.map",
        wmsLayer: "HB.Habitat.fitoclimatica",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.45,
        description: "Classificazione fitoclimatica del territorio italiano",
      },
      {
        id: "rischio_beni_esposti_2",
        label: "S3. Rischio beni culturali esposti",
        color: "#c084fc",
        defaultOn: false,
        arcgisUrl: "https://www.pcn.minambiente.it/arcgis/rest/services/Rischio_beni_esposti/MapServer",
        wfsUrl: "https://wms.pcn.minambiente.it/ogc?service=wfs",
        srid: "32632",
        opacity: 0.55,
        description: "Beni culturali e ambientali esposti a rischio — PCN",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // VINCOLI REGIONALI — Geoportali ufficiali (senza lettera)
  // ══════════════════════════════════════════════════════════════

  // ── PUGLIA ──────────────────────────────────────────────────
  {
    id: "reg_puglia",
    label: "🇮🇹 Puglia",
    icon: "📍",
    layers: [
      {
        id: "puglia_pptr",
        label: "PPTR — Piano Paesaggistico",
        color: "#7c3aed",
        defaultOn: false,
        arcgisUrl: "https://webapps.sit.puglia.it/arcgis/rest/services/PPTR/PPTR_ambiti_paesaggistici/MapServer",
        opacity: 0.5,
        bounds: [39.78, 15.33, 42.23, 18.52],
        description: "Piano Paesaggistico Territoriale Regionale — ambiti paesaggistici",
      },
      {
        id: "puglia_vincolo_idro",
        label: "Vincolo idrogeologico Puglia",
        color: "#2563eb",
        defaultOn: false,
        arcgisUrl: "https://webapps.sit.puglia.it/arcgis/rest/services/Idrogeomorfologia/Vincolo_Idrogeologico/MapServer",
        opacity: 0.5,
        bounds: [39.78, 15.33, 42.23, 18.52],
        description: "Aree sottoposte a vincolo idrogeologico — Regione Puglia",
      },
      {
        id: "puglia_olivi",
        label: "Olivi monumentali (L.R. 14/2007)",
        color: "#65a30d",
        defaultOn: false,
        arcgisUrl: "https://webapps.sit.puglia.it/arcgis/rest/services/Agricoltura/Olivi_Monumentali/MapServer",
        opacity: 0.55,
        bounds: [39.78, 15.33, 42.23, 18.52],
        description: "Olivi monumentali e di pregio — L.R. Puglia 14/2007",
      },
      {
        id: "puglia_aree_non_idonee",
        label: "Aree non idonee FER Puglia",
        color: "#dc2626",
        defaultOn: false,
        arcgisUrl: "https://webapps.sit.puglia.it/arcgis/rest/services/Energia/Aree_non_idonee_FER/MapServer",
        opacity: 0.5,
        bounds: [39.78, 15.33, 42.23, 18.52],
        description: "Aree non idonee FER — R.R. Puglia 24/2010",
      },
      {
        id: "puglia_usi_civici",
        label: "Usi civici Puglia",
        color: "#78716c",
        defaultOn: false,
        arcgisUrl: "https://webapps.sit.puglia.it/arcgis/rest/services/Demanio/Usi_civici/MapServer",
        opacity: 0.5,
        bounds: [39.78, 15.33, 42.23, 18.52],
        description: "Terreni gravati da usi civici — Regione Puglia",
      },
      {
        id: "puglia_vincoli_delegati_art142",
        label: "Vincoli paesaggistici Art.142 (PPTR Puglia)",
        color: "#7c3aed",
        defaultOn: false,
        arcgisUrl: "https://webapps.sit.puglia.it/arcgis/rest/services/Operationals/VincoliDelegati/MapServer",
        arcgisLayers: "show:2,5,6,7,8,9,10,11,12",
        opacity: 0.5,
        bounds: [39.78, 15.33, 42.23, 18.52],
        description: "Vincoli paesaggistici Art.142 (fiumi, boschi, macchie, zone umide, parchi) — PPTR Puglia delegati",
      },
    ],
  },

  // ── BASILICATA ──────────────────────────────────────────────
  {
    id: "reg_basilicata",
    label: "🇮🇹 Basilicata",
    icon: "📍",
    layers: [
      {
        id: "basilicata_pai",
        label: "PAI Basilicata",
        color: "#dc2626",
        defaultOn: false,
        wmsUrl: "https://rsdi.regione.basilicata.it/rbgeoserver2016/wms",
        wmsLayer: "rsdi:pai_frane",
        opacity: 0.5,
        bounds: [39.89, 15.33, 41.14, 16.87],
        description: "PAI pericolosità frana — RSDI Regione Basilicata",
      },
      {
        id: "basilicata_vincolo_idro",
        label: "Vincolo idrogeologico Basilicata",
        color: "#2563eb",
        defaultOn: false,
        wmsUrl: "https://rsdi.regione.basilicata.it/rbgeoserver2016/wms",
        wmsLayer: "rsdi:vincolo_idrogeologico",
        opacity: 0.5,
        bounds: [39.89, 15.33, 41.14, 16.87],
        description: "Vincolo idrogeologico — RSDI Regione Basilicata",
      },
      {
        id: "basilicata_ppr",
        label: "Piano Paesaggistico Regionale (PPRB)",
        color: "#7c3aed",
        defaultOn: false,
        wmsUrl: "https://rsdi.regione.basilicata.it/rbgeoserver2016/wms",
        wmsLayer: "ppr:piano_paesaggistico",
        wfsUrl: "https://rsdi.regione.basilicata.it/rbgeoserver2016/wfs",
        wfsLayer: "ppr:piano_paesaggistico",
        opacity: 0.5,
        bounds: [39.89, 15.33, 41.14, 16.87],
        description: "Piano Paesaggistico Regionale Basilicata (PPRB) — vincoli paesaggistici D.Lgs. 42/2004",
      },
    ],
  },

  // ── CALABRIA ────────────────────────────────────────────────
  {
    id: "reg_calabria",
    label: "🇮🇹 Calabria",
    icon: "📍",
    layers: [
      {
        id: "calabria_pai",
        label: "PAI Calabria",
        color: "#dc2626",
        defaultOn: false,
        wmsUrl: "https://geoportale.regione.calabria.it/geoserver/wms",
        wmsLayer: "pai:pericolosita_frana",
        opacity: 0.5,
        bounds: [37.91, 15.63, 39.95, 17.13],
        description: "PAI pericolosità frana — Geoportale Regione Calabria",
      },
      {
        id: "calabria_vincolo_idro",
        label: "Vincolo idrogeologico Calabria",
        color: "#2563eb",
        defaultOn: false,
        wmsUrl: "https://geoportale.regione.calabria.it/geoserver/wms",
        wmsLayer: "rsdi:vincolo_idrogeologico",
        opacity: 0.5,
        bounds: [37.91, 15.63, 39.95, 17.13],
        description: "Vincolo idrogeologico R.D. 3267/1923 — Geoportale Regione Calabria",
      },
      {
        id: "calabria_parchi_regionali",
        label: "Parchi e riserve regionali Calabria",
        color: "#16a34a",
        defaultOn: false,
        wmsUrl: "https://geoportale.regione.calabria.it/geoserver/wms",
        wmsLayer: "aree_protette:parchi_regionali",
        opacity: 0.5,
        bounds: [37.91, 15.63, 39.95, 17.13],
        description: "Parchi naturali regionali e riserve — Regione Calabria",
      },
    ],
  },

  // ── TOSCANA ─────────────────────────────────────────────────
  {
    id: "reg_toscana",
    label: "🇮🇹 Toscana",
    icon: "📍",
    layers: [
      {
        id: "toscana_vincolo_paesaggistico",
        label: "Vincolo paesaggistico Toscana",
        color: "#a855f7",
        defaultOn: false,
        wmsUrl: "https://www502.regione.toscana.it/geoscopio/wms",
        wmsLayer: "PIANO_PAESAGGISTICO",
        opacity: 0.5,
        bounds: [42.24, 9.69, 44.47, 12.37],
        description: "Vincoli paesaggistici — GEOscopio Regione Toscana",
      },
      {
        id: "toscana_vincolo_idro",
        label: "Vincolo idrogeologico Toscana",
        color: "#2563eb",
        defaultOn: false,
        wmsUrl: "https://www502.regione.toscana.it/geoscopio/wms",
        wmsLayer: "VINCOLO_IDROGEOLOGICO",
        opacity: 0.5,
        bounds: [42.24, 9.69, 44.47, 12.37],
        description: "Vincolo idrogeologico — GEOscopio Regione Toscana",
      },
      {
        id: "toscana_uso_suolo",
        label: "Uso del suolo Toscana",
        color: "#65a30d",
        defaultOn: false,
        wmsUrl: "https://www502.regione.toscana.it/geoscopio/wms",
        wmsLayer: "USO_SUOLO",
        opacity: 0.5,
        bounds: [42.24, 9.69, 44.47, 12.37],
        description: "Carta dell'uso del suolo — GEOscopio Regione Toscana",
      },
    ],
  },

  // ── LOMBARDIA ───────────────────────────────────────────────
  {
    id: "reg_lombardia",
    label: "🇮🇹 Lombardia",
    icon: "📍",
    layers: [
      {
        id: "lombardia_vincolo_idro",
        label: "Vincolo idrogeologico Lombardia",
        color: "#2563eb",
        defaultOn: false,
        arcgisUrl: "https://www.cartografia.servizirl.it/arcgis2/rest/services/Idrogeologia/Vincolo_Idrogeologico/MapServer",
        opacity: 0.5,
        bounds: [44.68, 8.50, 46.64, 11.43],
        description: "Vincolo idrogeologico — Geoportale Lombardia",
      },
      {
        id: "lombardia_pgt",
        label: "PGT — Piani di Governo del Territorio",
        color: "#7c3aed",
        defaultOn: false,
        arcgisUrl: "https://www.cartografia.servizirl.it/arcgis2/rest/services/Urbanistica/PGT_mosaico/MapServer",
        opacity: 0.45,
        bounds: [44.68, 8.50, 46.64, 11.43],
        description: "Mosaicatura PGT comunali — Regione Lombardia",
      },
      {
        id: "lombardia_boschi",
        label: "DUSAF — Boschi e foreste Lombardia",
        color: "#166534",
        defaultOn: false,
        arcgisUrl: "https://www.cartografia.servizirl.it/arcgis2/rest/services/Ambiente/Uso_suolo_DUSAF/MapServer",
        opacity: 0.5,
        bounds: [44.68, 8.50, 46.64, 11.43],
        description: "DUSAF — Destinazione d'Uso dei Suoli Agricoli e Forestali",
      },
    ],
  },

  // ── CAMPANIA ────────────────────────────────────────────────
  {
    id: "reg_campania",
    label: "🇮🇹 Campania",
    icon: "📍",
    layers: [
      {
        id: "campania_pai",
        label: "PAI Campania",
        color: "#dc2626",
        defaultOn: false,
        opacity: 0.5,
        bounds: [39.99, 13.76, 41.51, 15.81],
        description: "PAI pericolosità — Regione Campania. Richiede autenticazione, inserire URL alternativo nei settings.",
      },
      {
        id: "campania_vincolo_paesaggistico",
        label: "Vincolo paesaggistico Campania",
        color: "#a855f7",
        defaultOn: false,
        opacity: 0.5,
        bounds: [39.99, 13.76, 41.51, 15.81],
        description: "Vincoli paesaggistici — Regione Campania. Richiede autenticazione, inserire URL alternativo nei settings.",
      },
    ],
  },

  // ── SICILIA ─────────────────────────────────────────────────
  {
    id: "reg_sicilia",
    label: "🇮🇹 Sicilia",
    icon: "📍",
    layers: [
      {
        id: "sicilia_pai",
        label: "PAI Sicilia",
        color: "#dc2626",
        defaultOn: false,
        wmsUrl: "https://www.sitr.regione.sicilia.it/geoserver/wms",
        wmsLayer: "pai:pericolosita_geomorfologica",
        opacity: 0.5,
        bounds: [36.64, 12.43, 38.82, 15.65],
        description: "PAI pericolosità geomorfologica — SITR Regione Sicilia",
      },
      {
        id: "sicilia_vincolo_idro",
        label: "Vincolo idrogeologico Sicilia",
        color: "#2563eb",
        defaultOn: false,
        wmsUrl: "https://www.sitr.regione.sicilia.it/geoserver/wms",
        wmsLayer: "rsdi:vincolo_idrogeologico",
        opacity: 0.5,
        bounds: [36.64, 12.43, 38.82, 15.65],
        description: "Vincolo idrogeologico R.D. 3267/1923 — SITR Regione Sicilia",
      },
      {
        id: "sicilia_vincoli_paesaggistici",
        label: "Vincoli paesaggistici Sicilia",
        color: "#a855f7",
        defaultOn: false,
        opacity: 0.5,
        bounds: [36.64, 12.43, 38.82, 15.65],
        description: "Vincoli paesaggistici — Regione Sicilia. Inserire URL nei settings.",
      },
      {
        id: "sicilia_aree_non_idonee",
        label: "Aree non idonee FER Sicilia",
        color: "#b91c1c",
        defaultOn: false,
        opacity: 0.5,
        bounds: [36.64, 12.43, 38.82, 15.65],
        description: "Aree non idonee FER — Regione Sicilia. Inserire URL nei settings.",
      },
    ],
  },

  // ── LAZIO ───────────────────────────────────────────────────
  {
    id: "reg_lazio",
    label: "🇮🇹 Lazio",
    icon: "📍",
    layers: [
      {
        id: "lazio_ptpr",
        label: "PTPR — Piano Paesistico Lazio",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [41.18, 11.45, 42.84, 14.03],
        description: "PTPR — Tavole A (beni paesaggistici) — Regione Lazio. Inserire URL nei settings.",
      },
      {
        id: "lazio_vincolo_idro",
        label: "Vincolo idrogeologico Lazio",
        color: "#2563eb",
        defaultOn: false,
        opacity: 0.5,
        bounds: [41.18, 11.45, 42.84, 14.03],
        description: "Vincolo idrogeologico — Regione Lazio. Inserire URL nei settings.",
      },
    ],
  },

  // ── VENETO ──────────────────────────────────────────────────
  {
    id: "reg_veneto",
    label: "🇮🇹 Veneto",
    icon: "📍",
    layers: [
      {
        id: "veneto_pai",
        label: "PAI Veneto",
        color: "#dc2626",
        defaultOn: false,
        opacity: 0.5,
        bounds: [44.79, 10.62, 46.68, 13.10],
        description: "PAI pericolosità — Regione Veneto. Inserire URL nei settings.",
      },
      {
        id: "veneto_vincolo_paesaggistico",
        label: "Vincolo paesaggistico Veneto",
        color: "#a855f7",
        defaultOn: false,
        opacity: 0.5,
        bounds: [44.79, 10.62, 46.68, 13.10],
        description: "Vincoli paesaggistici — Regione Veneto. Inserire URL nei settings.",
      },
    ],
  },

  // ── PIEMONTE ────────────────────────────────────────────────
  {
    id: "reg_piemonte",
    label: "🇮🇹 Piemonte",
    icon: "📍",
    layers: [
      {
        id: "piemonte_ppr",
        label: "PPR — Piano Paesaggistico Piemonte",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [44.06, 6.63, 46.46, 9.21],
        description: "Piano Paesaggistico Regionale — Piemonte. Inserire URL nei settings.",
      },
      {
        id: "piemonte_vincolo_idro",
        label: "Vincolo idrogeologico Piemonte",
        color: "#2563eb",
        defaultOn: false,
        opacity: 0.5,
        bounds: [44.06, 6.63, 46.46, 9.21],
        description: "Vincolo idrogeologico — Regione Piemonte. Inserire URL nei settings.",
      },
    ],
  },

  // ── EMILIA-ROMAGNA ──────────────────────────────────────────
  {
    id: "reg_emilia",
    label: "🇮🇹 Emilia-Romagna",
    icon: "📍",
    layers: [
      {
        id: "emilia_ptpr",
        label: "PTPR Emilia-Romagna",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [43.73, 9.20, 45.14, 12.76],
        description: "Piano Territoriale Paesistico Regionale — Emilia-Romagna. Inserire URL nei settings.",
      },
      {
        id: "emilia_vincolo_idro",
        label: "Vincolo idrogeologico Emilia-Romagna",
        color: "#2563eb",
        defaultOn: false,
        opacity: 0.5,
        bounds: [43.73, 9.20, 45.14, 12.76],
        description: "Vincolo idrogeologico — Regione Emilia-Romagna. Inserire URL nei settings.",
      },
    ],
  },

  // ── SARDEGNA ────────────────────────────────────────────────
  {
    id: "reg_sardegna",
    label: "🇮🇹 Sardegna",
    icon: "📍",
    layers: [
      {
        id: "sardegna_ppr",
        label: "PPR — Piano Paesaggistico Sardegna",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [38.86, 8.13, 41.26, 9.83],
        description: "Piano Paesaggistico Regionale — Sardegna. Inserire URL nei settings.",
      },
      {
        id: "sardegna_vincolo_idro",
        label: "Vincolo idrogeologico Sardegna",
        color: "#2563eb",
        defaultOn: false,
        opacity: 0.5,
        bounds: [38.86, 8.13, 41.26, 9.83],
        description: "Vincolo idrogeologico — Regione Sardegna. Inserire URL nei settings.",
      },
    ],
  },

  // ── ABRUZZO ─────────────────────────────────────────────────
  {
    id: "reg_abruzzo",
    label: "🇮🇹 Abruzzo",
    icon: "📍",
    layers: [
      {
        id: "abruzzo_pai",
        label: "PAI Abruzzo",
        color: "#dc2626",
        defaultOn: false,
        opacity: 0.5,
        bounds: [41.68, 13.02, 42.89, 14.79],
        description: "PAI pericolosità — Regione Abruzzo. Inserire URL nei settings.",
      },
      {
        id: "abruzzo_vincolo_paesaggistico",
        label: "Vincolo paesaggistico Abruzzo",
        color: "#a855f7",
        defaultOn: false,
        opacity: 0.5,
        bounds: [41.68, 13.02, 42.89, 14.79],
        description: "Vincoli paesaggistici — Regione Abruzzo. Inserire URL nei settings.",
      },
    ],
  },

  // ── MOLISE ──────────────────────────────────────────────────
  {
    id: "reg_molise",
    label: "🇮🇹 Molise",
    icon: "📍",
    layers: [
      {
        id: "molise_pai",
        label: "PAI Molise",
        color: "#dc2626",
        defaultOn: false,
        opacity: 0.5,
        bounds: [41.36, 13.94, 41.91, 15.17],
        description: "PAI pericolosità — Regione Molise. Inserire URL nei settings.",
      },
    ],
  },

  // ── LIGURIA ─────────────────────────────────────────────────
  {
    id: "reg_liguria",
    label: "🇮🇹 Liguria",
    icon: "📍",
    layers: [
      {
        id: "liguria_ptcp",
        label: "PTCP Liguria",
        color: "#7c3aed",
        defaultOn: false,
        arcgisUrl: "https://srvcarto.regione.liguria.it/arcgis/rest/services/Paesaggio/PTCP/MapServer",
        opacity: 0.5,
        bounds: [43.78, 7.49, 44.68, 10.07],
        description: "Piano Territoriale di Coordinamento Provinciale — Liguria",
      },
      {
        id: "liguria_vincolo_idro",
        label: "Vincolo idrogeologico Liguria",
        color: "#2563eb",
        defaultOn: false,
        arcgisUrl: "https://srvcarto.regione.liguria.it/arcgis/rest/services/Difesa_Suolo/Vincolo_Idrogeologico/MapServer",
        opacity: 0.5,
        bounds: [43.78, 7.49, 44.68, 10.07],
        description: "Vincolo idrogeologico — Regione Liguria",
      },
    ],
  },

  // ── MARCHE ──────────────────────────────────────────────────
  {
    id: "reg_marche",
    label: "🇮🇹 Marche",
    icon: "📍",
    layers: [
      {
        id: "marche_ppar",
        label: "PPAR Marche",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [42.69, 12.08, 43.97, 13.92],
        description: "Piano Paesistico Ambientale Regionale — Marche. Inserire URL nei settings.",
      },
      {
        id: "marche_vincolo_idro",
        label: "Vincolo idrogeologico Marche",
        color: "#2563eb",
        defaultOn: false,
        opacity: 0.5,
        bounds: [42.69, 12.08, 43.97, 13.92],
        description: "Vincolo idrogeologico — Regione Marche. Inserire URL nei settings.",
      },
    ],
  },

  // ── UMBRIA ──────────────────────────────────────────────────
  {
    id: "reg_umbria",
    label: "🇮🇹 Umbria",
    icon: "📍",
    layers: [
      {
        id: "umbria_ppr",
        label: "PPR Umbria",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [42.37, 12.07, 43.61, 13.26],
        description: "Piano Paesaggistico Regionale — Umbria. Inserire URL nei settings.",
      },
    ],
  },

  // ── FRIULI VENEZIA GIULIA ──────────────────────────────────
  {
    id: "reg_fvg",
    label: "🇮🇹 Friuli Venezia Giulia",
    icon: "📍",
    layers: [
      {
        id: "fvg_ppr",
        label: "PPR Friuli Venezia Giulia",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [45.58, 12.31, 46.65, 13.92],
        description: "Piano Paesaggistico Regionale — FVG. Inserire URL nei settings.",
      },
      {
        id: "fvg_vincolo_idro",
        label: "Vincolo idrogeologico FVG",
        color: "#2563eb",
        defaultOn: false,
        opacity: 0.5,
        bounds: [45.58, 12.31, 46.65, 13.92],
        description: "Vincolo idrogeologico — Regione FVG. Inserire URL nei settings.",
      },
    ],
  },

  // ── TRENTINO-ALTO ADIGE ────────────────────────────────────
  {
    id: "reg_trentino",
    label: "🇮🇹 Trentino-Alto Adige",
    icon: "📍",
    layers: [
      {
        id: "trentino_pup",
        label: "PUP Trentino",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [45.67, 10.38, 47.09, 12.48],
        description: "Piano Urbanistico Provinciale — Provincia Autonoma di Trento. Inserire URL nei settings.",
      },
    ],
  },

  // ── VALLE D'AOSTA ──────────────────────────────────────────
  {
    id: "reg_vda",
    label: "🇮🇹 Valle d'Aosta",
    icon: "📍",
    layers: [
      {
        id: "vda_ptp",
        label: "PTP Valle d'Aosta",
        color: "#7c3aed",
        defaultOn: false,
        opacity: 0.5,
        bounds: [45.47, 6.80, 45.99, 7.94],
        description: "Piano Territoriale Paesistico — Valle d'Aosta. Inserire URL nei settings.",
      },
    ],
  },
];

// Flat map for easy lookup
export const ALL_LAYERS: LayerDef[] = LAYER_GROUPS.flatMap(g => g.layers);
